name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  SQLX_FEATURES: "rustls,postgres"

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings

  test:
    name: Build & Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install sqlx-cli --features ${{ env.SQLX_FEATURES }} --locked
      - run: sudo apt-get install libpq-dev -y SKIP_DOCKER=true ./scripts/init_db.sh
      - run: cargo test --all-features

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-tarpaulin
      - run: cargo tarpaulin --ignore-tests

  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-audit
      - run: cargo audit
