name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: baptiste0928/cargo-install@v1
        with:
          crate: sqlx-cli
          args: --no-default-features --features rustls,postgres
      - run: sudo apt-get install -y libpq-dev
      - run: SKIP_DOCKER=true ./scripts/init_db.sh

      - run: cargo clippy -- -D warnings
      - run: cargo fmt --all -- --check
      - run: cargo test --all-features

      - uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-tarpaulin
      - run: cargo tarpaulin --ignore-tests

      - uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-audit
      - run: cargo audit
