name: Deploy to Fly

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      # https://community.fly.io/t/tips-to-run-database-migration-within-a-github-action/9739/3?u=galah92
      - uses: denoland/setup-deno@v1
      - uses: baptiste0928/cargo-install@v1
        with:
          crate: sqlx-cli
          args: --no-default-features --features rustls,postgres
      - run: deno run --allow-run --allow-env scripts/migrate.ts
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          POSTGRES_APP_NAME: ${{ secrets.POSTGRES_APP_NAME }}

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
